packages:
    - "apps/*"
    - "packages/*"

allowBuilds:
  argon2: set this to true or false
  protobufjs: true
  unrs-resolver: true

catalog:
    "@types/node": "^24"
    "typescript": "^6"
    "tsdown": "^0.22.14"
    "eslint": "^10.8.1"
